spring:
  datasource:
    #设备接入数据库连接
      iotaccess:
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true
        url: jdbc:mysql://139.129.100.51:3306/fire_cloud_server?characterEncoding=UTF-8
        username: tb-aliyun
        password: Ss!@#123

    #云大管理系统数据库连接
      smartcity:
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true
        url: jdbc:mysql://139.129.100.51:3306/xboot?characterEncoding=UTF-8
        username: tb-aliyun
        password: Ss!@#123

#通用终端配置文件
tyterminal:
  path: /etc/serverConfig.properties
  pic: /opt/screenshot/
  header: http://139.129.100.51


#拓深对应的我们的公司号，用来生成token
tpson:
#company 会被获取为2，而不是000002
  company: 000002
  ip: http://219.147.8.30:801
  relay: /gateway/device/ctl/smr3002/setRelay
  getToken: /gateway/certification
  learn: /gateway/device/ctl/smr3002/learn


