#server:
#  port: 31015
#
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.16.20.191:3306/fire_protection?characterEncoding=UTF-8
#      username: root
#      password: 123456
#
