#server:
#  port: 31015
#
#spring:
#  datasource:
#    druid:
#      url: jdbc:mysql://172.16.20.191:3306/fire_protection?characterEncoding=UTF-8
#      username: root
#      password: 123456



spring:
  datasource:
    iotaccess:
      url: jdbc:mysql://172.16.20.83:3306/fire_cloud_server?characterEncoding=UTF-8
      username: root
      password: S!@#s123


#通用终端配置文件
tyterminal:
  path: /app/deploy/jars/serverConfig.properties

#拓深对应的我们的公司号，用来生成token
tpson:
  company: 000002
  ip: http://219.147.8.30:801
  relay: /gateway/device/ctl/smr3002/setRelay
  getToken: /gateway/certification
  learn: /gateway/device/ctl/smr3002/learn