#server:
#  port: 31015
#
#spring:
#  datasource:
#    druid:
#      url: jdbc:mysql://172.16.20.191:3306/fire_protection?characterEncoding=UTF-8
#      username: root
#      password: 123456



spring:
  datasource:
    url: jdbc:mysql://172.16.20.83:3306/fire_cloud_server?characterEncoding=UTF-8
    username: root
    password: S!@#s123



